### ISSUE TITLE
Error message trying to run the `Chiofz()` function (AttributeError)

### ISSUE THREAD

**Issue by reikonakajima** [surhudm/aum#6]
I  get an error message trying to run the `Chiofz()` function:
```
>>> print a.Chiofz(2.0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/reiko/2code/aum/install/lib/python2.7/site-packages/cosmology.py", line 364, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, cosmology, name)
  File "/Users/reiko/2code/aum/install/lib/python2.7/site-packages/cosmology.py", line 54, in _swig_getattr
    raise AttributeError(name)
AttributeError: Chiofz
```
Thanks for your help, Surhud.

**Comment by surhudm** [comment]
This is a problem of the documentation. I apologize, the function Chiofz was recently removed from the public functions in aum, you need to use Dcofz for getting the comoving distance.

Thanks for reporting this.

**Comment by surhud** [comment]
I have updated the instructions in the commit I pushed just now. It also
tells you how to see the documentation for the cosmology module. If you are
using ipython you should be able to also interactively complete commands
using tab.

Sorry the documentation is not fully complete yet, the code was put on
github in a hurry, but I promise I will work on it.

**Comment by reikonakajima** [comment]
Thanks.  I guess this issue can be closed now?  By the way, if you have any good SWIG tutorial sites you can point me to, I would be grateful.

**Comment by surhud** [comment]
Here it is:

http://www.swig.org/tutorial.html

This is important if you are considering adding some extra functionality to
the swig interface file (mostly you should not have to do this). If your
main aim is to use the code, then you should not have to learn swig.

Surhud

**Comment by reikonakajima** [comment]
Thanks.  I'll only be using it in the beginning; then "feature addition" will come later (at least that's the plan).
