### ISSUE TITLE
Setting HOD parameters causes core dump

### ISSUE THREAD

**Issue by reikonakajima** [surhudm/aum#9]
Hello Surhud,

I've run the following simple script to set HOD parameters (a straight copy from the examples in the python help file).  It proceeds without a problem until it tries to calculate D2gg_num(), upon which GSL throws an error:

```
#!/usr/bin/env python                                                                                 
import sys
from math import *
sys.path.append('/users/reiko/2code/aum/install/lib/python2.7/site-packages')
import hod as h


## BEGIN: main function                                                                               
if __name__=='__main__':

    cosmo = h.cosmo()
    cosmo.Om0 = 0.307115
    cosmo.w0 = -1
    cosmo.wa = 0
    cosmo.Omk = 0.0
    cosmo.hval = 0.6777
    cosmo.Omb = 0.048206
    cosmo.th = 2.726
    cosmo.s8 = 0.8228
    cosmo.nspec = 0.96
    cosmo.ximax = log10(8.0)

    hodp = h.hodpars()
    hodp.cfac = 1.0
    hodp.Mmin = 13.0
    hodp.siglogM = 0.5
    hodp.Msat = 14.0
    hodp.alpsat = 1.0
    hodp.Mcut = 13.5
    hodp.csbycdm = 1.0
    hodp.fac = 1.0

    a = h.hod(cosmo, hodp)  # gsl error "function value is not finite"                                
    #a = h.hod()            # calculates D2gg_num without any problems                                

    kk = 0.1
    z = 0.5
    print( a.D2gg_num( kk, z ) )
```
and the corresponding error message is:
```
gsl: brent.c:57: ERROR: function value is not finite
Default GSL error handler invoked.
Aborted (core dumped)
```
When I run the HOD in the default, it calculates `D2gg_num` without any problem.  Would you know how/where to fix it?

Cheers, Reiko

**Comment by surhudm** [comment]
Hi Reiko,

Sorry for the delay in my reply, am in between switching laptops. Thanks for reporting the issue.

The problem with the code you wrote above is that cfac is not a member of hodp, but of cosmo structure. If you replace hodp.cfac=1.0 with cosmo.cfac=1.0, the code runs perfectly fine. Can you please confirm it?

You said you copied straight from examples in help file, can you tell me which file this was? It may be an errors in the docs in case I wrote hodp.cfac anywhere.

One issue I realize is that the swigged python does not complain if the structure does not have a particular parameter you are setting up. I dont know why this is the case. I will check with a simpler code to figure out if this can be done.

Cheers,
Surhud

**Comment by reikonakajima** [comment]
Hi Surhud,

> If you replace hodp.cfac=1.0 with cosmo.cfac=1.0, the code runs perfectly fine. Can you please confirm it?

Yup, you're right.  AUM ran without a hitch.

> You said you copied straight from examples in help file, can you tell me which file this was? 

It would have been in hod_wrap.cpp, except that apparently I copy-pasted it wrong for that one line.  Sorry for the trouble!  Now I can play more fully with aum.  Thanks!

**Comment by surhudm** [comment]
@reikonakajima I tried to figure out how to avoid this kind of mistake, and it seems there is a possibility for that in swig, however swig developers may be considering removing it altogether (see swig/swig#719)
